version: '3.8'

services:
  backend:
    image: node:18
    container_name: backend
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - "./server:/server"  # Mount the local 'server' directory to '/server' inside the container
    working_dir: /server      # Set the working directory to '/server' inside the container
    environment:
      - MONGODB_URI=mongodb://achref:achref@mongo:27017
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "./client:/client"
      - /client/node_modules  # Ensure node_modules are not overwritten by the volume

  mongo:
    image: mongo
    restart: always
    container_name: mongo-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: achref
      MONGO_INITDB_ROOT_PASSWORD: achref
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}  # Persistent volume for MongoDB data
