apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MONGO_URI: "mongodb://achref:achref@mongo:27017/crud?authSource=admin"
  PORT: "4000"
  REACT_APP_SERVER_URL: "http://server-service:4000"