apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-achref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-achref
  template:
    metadata:
      labels:
        app: mongo-achref
      
    spec:
      containers:
      - name: mongo-achref
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "achref"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "achref"
      - name: mongodb-exporter
        image: bitnami/mongodb-exporter:latest
        ports:
        - containerPort: 9216
        env:
        - name: MONGODB_URI
          value: "mongodb://achref:achref@mongo:27017"