apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-stockoverflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-stockoverflow
  template:
    metadata:
      labels:
        app: server-stockoverflow
      
    spec:
      containers:
      - name: server-stockoverflow
        image: achrafsola/backend:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: app-configmap